### ISSUE TITLE
Bump android version to Android 9/Pie

### ISSUE THREAD

**Issue by T2hhbmEK** [viperML/qemu-android-x86#3]
I've found that android 9(pie) works just fine for me with an AMD GPU.
Maybe we should bump android version to 9.0 r2 in master branch(which keeps track with AUR version), and maintain a nougat branch separately. Every time master updates, just rebase nougat branch against it. It should be trivial.

**Comment by viperML** [comment]
9.0 r2 won't boot on my system. You may want to keep your fork updated

**Comment by viperML** [comment]
@T2hhbmEK if you are interested, I am currently refactoring the installation procedure which will allow to use any android version independently of this repo.

**Comment by T2hhbmEK** [comment]
I've been using virt-manager to manage my QEMU Android box for some days. Thanks anyway.
