### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Pakrohk** [viperML/qemu-android-x86#4]
Hello, I installed the package through aur, after running it in the terminal, I get a black screen and Android does not boot, What do you think is my solution ?! 
![image](https://cdn.discordapp.com/attachments/832990499659841537/909610501594562590/Screenshot_20211115_043653.png)
![image2](https://cdn.discordapp.com/attachments/832990499659841537/909613657699282974/Screenshot_20211115_044933.png)

**Comment by viperML** [comment]
This is not the repo for the AUR package, but rather a fork. Please wipe your `.config/android-x86` and install this repo.
